# Generated by Django 4.0.5 on 2022-06-14 14:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('POPUP', 'ポップアップ')], max_length=16, verbose_name='種別')),
                ('memo', models.TextField(blank=True, default='', null=True, verbose_name='メモ')),
            ],
            options={
                'verbose_name': '設定',
                'verbose_name_plural': '設定',
            },
        ),
        migrations.CreateModel(
            name='Where',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uri', models.CharField(max_length=2048, verbose_name='URI')),
                ('protocol', models.CharField(max_length=32, verbose_name='プロトコル')),
                ('hostname', models.CharField(max_length=512, verbose_name='ホスト名')),
                ('pathname', models.CharField(max_length=2048, verbose_name='パス名')),
                ('memo', models.TextField(blank=True, default='', null=True, verbose_name='メモ')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uri.config')),
            ],
            options={
                'verbose_name': '条件式',
                'verbose_name_plural': '条件式',
            },
        ),
    ]
