# Generated by Django 4.0.5 on 2022-06-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='where',
            name='hostname',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='ホスト名'),
        ),
        migrations.AlterField(
            model_name='where',
            name='pathname',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='パス名'),
        ),
        migrations.AlterField(
            model_name='where',
            name='protocol',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='プロトコル'),
        ),
        migrations.AlterField(
            model_name='where',
            name='uri',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='URI'),
        ),
    ]
